### ISSUE TITLE
Web-App sometimes does not display comments and photos

### ISSUE THREAD

**Issue by tdilo** [openchargemap/ocm-app#10]
Sometimes the webapp (in the browser) does not display any comments and photos in the charger information dialog. Reloading the complete page is required to see them again. This happened several times after editing with the new editor, but may also have happened on its own.
I'm not sure how to reproduce yet.

**Comment by webprofusion-chrisc** [comment]
Thanks, will investigate. The refresh button (when viewing a POI) should reload all that info. Photos in particular have some lag just after they get uploaded while we convert them into different sizes and upload the variations to S3 storage.

**Comment by webprofusion-chrisc** [comment]
Actually I think we are skipping the load of comments/photos on refresh, will fix.

**Comment by webprofusion-chrisc** [comment]
Closing as I assume this was fixed, please revert if still an issue.
