### ISSUE TITLE
New editor does not set charging level

### ISSUE THREAD

**Issue by tdilo** [openchargemap/ocm-app#11]
The new editor does not set (or allow entering) the charging level field. This results in new entries which do not have the appropriate color in the map.

**Comment by webprofusion-chrisc** [comment]
Thanks, we should make this automatically populated (and re-calculated) based on kW power and make at least kW mandatory for user supplied equipment information. Level has been of limited usefulness since the start so we should try to retire it.

**Comment by webprofusion-chrisc** [comment]
Closing. This is now auto calculated.
