### ISSUE TITLE
Add Schuko icon file

### ISSUE THREAD

**Issue by Gabor111a** [openchargemap/ocm-app#22]
I drown schuko svg icon, please add it to Open Charge Map.
[schuko.zip](https://github.com/openchargemap/ocm-app/files/6051723/schuko.zip)

{
“FormalName”: “CEE 7/4”,
“IsDiscontinued”: false,
“IsObsolete”: false,
“ID”: 28,
“Title”: “CEE 7/4 - Schuko - Type F”
},

**Comment by webprofusion-chrisc** [comment]
Thanks! This will be updated on https://map.openchargemap.io shortly and on mobile apps when we next update those.
