### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by pietervdvn** [openchargemap/ocm-app#23]
Hi,

I would like to reuse some of your icons for a similar project. Is that possible? If so, under what license?

**Comment by pietervdvn** [comment]
Seems like I overlooked the license file, linking to https://commons.wikimedia.org/wiki/EV_Charger_Gallery

**Comment by webprofusion-chrisc** [comment]
Yeah, one is original (Schuko) and would be MIT licensed. Noticed I'd forgot to set the license file in the repo, fixed now.

**Comment by pietervdvn** [comment]
Excellent, thanks a lot!
