### ISSUE TITLE
Add Location always defaults to Australia

### ISSUE THREAD

**Issue by zymurgic** [openchargemap/ocm-app#26]
While very convenient for users in Australia, the Add Location via the map always defaults the Country in the address to Australia.

The main website Add A Location code has a reverse geocode for the address, which is good for most locations not near disputed border regions, and is better than simply assuming everywhere is Australia.

**Comment by webprofusion-chrisc** [comment]
Hmm, the "happy path" that's supposed to work is:
- user taps the blue marker to add a charging spot at that location (or just choose "add location" from the menu)
- app guesses the nearest address
- users clicks, "use this address", app sets the country from that.

Would it be better to not wait for the user to click 'Use This Address" and just use the reverse geocoded country anyway? I'm kind of assuming that people are placing the marker first, then using the suggested address before manually correcting stuff.

**Comment by zymurgic** [comment]
I'd guess so. As an editor, I'm seeing lots of entries with just a location title and address of "Australia".

**Comment by webprofusion-chrisc** [comment]
Thinks this was fixed a while ago, basically if you don't specify an address it's rejected by the API.
