### ISSUE TITLE
Editor showing old data

### ISSUE THREAD

**Issue by ProjectMoon** [openchargemap/ocm-app#27]
When I try to edit data on a charging location, often the old data is shown instead on the equipment section, making editing essentially impossible. The node in question is OCM-16596, and it seems to be showing the old equipment more than 50% of the time when I load the edit dialog.

**Comment by webprofusion-chrisc** [comment]
This sounds like an old caching issue. Closing for now but please re-open if this is a still and issue. Changes only get applied to POIs after approval by a country editor, so compound edits (going back to change an edit that hasn't been published yet) don't work.
