### ISSUE TITLE
Firefox: black map with error Failed to initialize WebGL

### ISSUE THREAD

**Issue by ronald** [openchargemap/ocm-app#29]
We often have the problem in Firefox 96 on Windows10/11 that the map stays black and only the markers are visible.

The firefox-console shows: Failed to initialize WebGL.

Link example: https://map.openchargemap.io/?mode=embedded&languagecode=de&latitude=53.773517&longitude=12.575576

**Comment by webprofusion-chrisc** [comment]
Thanks for raising this issue. If I try Firefox 96 on Windows 11 your link works fine. We currently use Mapbox GL JS for our maps. Do their example maps work for you? https://docs.mapbox.com/mapbox-gl-js/example/

For example: https://docs.mapbox.com/mapbox-gl-js/example/simple-map/

**Comment by gosferano** [comment]
Not the author, but got this issue myself. Maps are not loading, getting errors that WebGL failed to initialize.

On the example page you provided I am getting this:
> Mapbox GL unsupported
> Mapbox GL requires [WebGL support](https://caniuse.com/#feat=webgl). Please check that you are using a supported browser and that [WebGL is enabled](https://get.webgl.org/).

Firefox version: 104.0.2 (64-bit)

It works just fine on Chrome.

**Comment by webprofusion-chrisc** [comment]
Sorry we are not part of either MapBox or Firefox. You should raise the issue with either of them.

**Comment by webprofusion-chrisc** [comment]
If these maps don't work for you then neither will ours: https://docs.mapbox.com/mapbox-gl-js/example/simple-map/

**Comment by webprofusion-chrisc** [comment]
This is https://map.openchargemap.io running in Firefox 104.0.2 - 64-bit, Windows.

![image](https://user-images.githubusercontent.com/2445502/189883160-d3011605-30d1-4d96-948e-572742f66f73.png)

**Comment by ronald** [comment]
The bug was not reliably reproducible and is not reproducible today - I could certainly have formulated that in more detail. Sorry.
I understand that the bug is closed.
But https://github.com/openchargemap/ocm-app/issues/29#issuecomment-1245064070 shows that the problem still occurs.

Even if the actual problem is with Firefox/Mapbox, as a non ocm-map developer I wouldn't know how to submit the problem there.

**Comment by webprofusion-chrisc** [comment]
Thanks @ronald I was just responding to @gosferano who had found the same problem, however in general the bug is outside of the scope of things we can influence, which is why I closed the issue.

**Comment by gosferano** [comment]
Thank you. I got an FF update ready for installation and it started working after the restart. Will report to MapBox or FF if the issue arises again.
