### ISSUE TITLE
Website editor broken - edits not saved

### ISSUE THREAD

**Issue by Samuel12321** [openchargemap/ocm-app#30]
![Screenshot 2022-07-02 182254](https://user-images.githubusercontent.com/35312698/176989290-3347cf5b-3544-4373-9cf9-b9639443e35f.png)

when the user clicks the submit button, the please wait message appears but the edits are not saved and the edit popup is not closed.

Browser = Microsoft Edge (chromium) Version 103.0.1264.44
OS: Windows 11

Edits on the Android app still work

**Comment by webprofusion-chrisc** [comment]
Edit worked ok for me, was the address info populated?  May be worth signing out of the app and back in again.

 If the problem persists please open the chrome developer tools and perform an edit, then look for either javascript or network errors.

**Comment by Samuel12321** [comment]
ok tried that and got this error: `polyfills.78ab2427ed412942.js:1 POST https://api.openchargemap.io/v3/poi/ 401`

Failed to load resource: the server responded with a status of 401 () api.openchargemap.io/v3/poi/:1

**Comment by Samuel12321** [comment]
> Edit worked ok for me, was the address info populated? May be worth signing out of the app and back in again.
> 
this happened on multiple different attempts on different days 
- tried signing out then back in again

**Comment by Samuel12321** [comment]
ok well after a browser reset, it seems to be working
