### ISSUE TITLE
Android app not visible in Play Store for some devices/countries

### ISSUE THREAD

**Issue by iboboc** [openchargemap/ocm-app#33]
Android application available in Google Play Store https://play.google.com/store/apps/details?id=com.webprofusion.openchargemap is not visible/cannot be installed on some devices "This app is available for some of your devices".

The phone is Samsung S23 Ultra (Android 13, SDK33, ARMv8-A/arm64-v8a), country Romania.

Thanks.

**Comment by webprofusion-chrisc** [comment]
I've published an update today so you might be able to find it now. Your Romanian language change is not yet included but will be in the next update.

**Comment by iboboc** [comment]
I can confirm it is working, app is available and can be installed. Thanks!
