### ISSUE TITLE
Improve Add / Edit charger pages

### ISSUE THREAD

**Issue by Felger** [openchargemap/ocm-app#4]
As is, the add/edit pages are difficult to use.  Some small modifications would go a long way to making them easier for users to update the charge map.  Suggestions:

- Show only the minimum fields needed.  Hide "additional" field under expanders to reduce clutter.  Examples:  
  - Address Line 2
  - Additional Location Details could be entirely hidden, perhaps under multiple expanders (contact info, access info, website)
  - Equipment Details could show only Connection Type and Power at minimum, other details can be extracted from these inputs.
- Filter operator by region.  By the time "Basic Information" is reached, a location has been input.  The Network / Operator dropdown is huge and difficult to search through.  This could be eased by filtering operators based on region. 
  - May not be doable, depending on operator region knowledge.  
  - Could develop this filter based on whether a given operator has a station within an arbitrary distance (1000 miles?) of the chosen location.
  - Could allow an override, (checkbox, "Filter operators by region"?)
- Equipment Details, connection type is also a very large list.  Would be nice to have filters for this.
  - Select Charging level first, grey out "Connection Type" until charging level is selected.  Filter connections by charging level.
  - Icons for connection types would aid in selecting the correct plug.  
  - Alternately, Level and Supply Type can be inferred from Max Power and Connection type, and would not need to be user input.
- For ease of directing users from external sites to the POI add page at a given location, it would be nice to allow a URL like:
```
https://openchargemap.org/site/poi/add&lat=37.2&lon=-99.1
```

**Comment by Felger** [comment]
My apologies if this is the wrong place for this issue, happy to move this to the system project if that's more appropriate.

**Comment by webprofusion-chrisc** [comment]
@Felger hi, great feedback and revisions to our Add workflow are long overdue. Technically this refers to the 'system' repo as thats where this is currently kept (it's an asp.net mvc website - server side rendering etc). I would however like to move the 'add' process to our app instead so that there is only one codebase to maintain for the add/edit workflow. The app is currently being updated (to ionic 4/angular 6) and would be the same on web, android app and ios app. It's one of the many projects I juggle so if you know any interested developers who could volunteer to help that would be great.

**Comment by Felger** [comment]
Same as you, I've got a number of projects I'm juggling, but at the very least I'll make it known that you're looking for help on this.  Would be great to get the new version of the app all nice and polished.

**Comment by webprofusion-chrisc** [comment]
@Felger we'll get there one day, and others showing interest does help it along and provide some motivation. 

On a tangent, would ABRP possibly have an API we could integrate with? Our current web app has a concept of Journeys (a series of saved waypoints) and sort of does a basic route query but routing in general is not really a priority. At the same time we have over 10k drivers per month who use the app (not a lot, but not insignificant) and it would be great to help them out with better services if the development can be kept to the minimum.

**Comment by Felger** [comment]
We haven't put much (read: any) work into a public API, but I don't think it'd be out of the question.  The problem for you is, to expand our coverage as much as possible, we pull from a ton of different databases, not just OCM, so when we return a route, odds are pretty good that it'll include non-OCM chargers.  I'll talk to Bo about whether it'd be worth opening that up, wouldn't be _too_ hard to implement an OCM filter on the planning request.

Speaking of, I still see you missing a lot of the NREL chargers, with so many new chargers popping up, might not be a bad idea to re-incorporate that to a more regular data pull.

**Comment by razzeee** [comment]
Tried to edit a location and got this.
![image](https://user-images.githubusercontent.com/5943908/71764284-4bf62600-2ee6-11ea-9671-23df5d057b3e.png)

I tried to empty the `Usage Cost`, as that station is for free

**Comment by razzeee** [comment]
Seems like I also get that when I try to add a new location. Did not get that some days ago.

**Comment by webprofusion-chrisc** [comment]
@Razzeee thanks, I'm away from a computer just now but I'd suspect the API is returning an error on submit, worth debugging in chrome network tab to see what the response actually is.

**Comment by webprofusion-chrisc** [comment]
@Razzeee resolved now.
