### ISSUE TITLE
Change charger icons

### ISSUE THREAD

**Issue by dav1312** [openchargemap/ocm-app#45]
Instead of adding a background to the images, change the color of the images
![image](https://github.com/user-attachments/assets/2279938c-8f64-4cac-a216-0621a338532e)

![image](https://github.com/user-attachments/assets/819f333f-64e1-4b43-8be9-947a33841112)

**Comment by webprofusion-chrisc** [comment]
Thanks, a fix for this (dynamic based on user light/dark theme pref) has now been deployed on web and android. iOS will get it when the iOS version next needs an update.
