### ISSUE TITLE
Charger POI Add Page does not show center pin on Chrome

### ISSUE THREAD

**Issue by Felger** [openchargemap/ocm-app#5]
Using Chrome 69.0.3497.92, I do not get a center pin on the add charging location map:
![image](https://user-images.githubusercontent.com/8065024/45567623-e88f4300-b81f-11e8-8ff9-c339ced62c7f.png)

The center pin does appear in firefox:
![image](https://user-images.githubusercontent.com/8065024/45567636-f5ac3200-b81f-11e8-92c2-1ae6a7968fa3.png)

**Comment by Felger** [comment]
My apologies if this is the wrong place for this issue, happy to move this to the system project if that's more appropriate.

**Comment by webprofusion-chrisc** [comment]
Thanks for raising this!
