### ISSUE TITLE
Usability of Network/Operator list

### ISSUE THREAD

**Issue by hchalkley** [openchargemap/ocm-app#8]
Having a single list of all the charging network operators worldwide makes it a bit cumbersome to use.
An option to only show providers in a selected country would make it much more user-friendly.
It would also be helpful to include a button to clear the selection.

**Comment by webprofusion-chrisc** [comment]
Hi, I agree completely. Some work was started to allow for filtering based on being active in a specific search region but is not completed. Things like Network Operators, Connector Types etc are all regional. You should still be able to pick something that not previously been chosen for the region you are in (like an unusual network operator etc) but agree the list we present initially should be restricted to locally relevant items.

**Comment by webprofusion-chrisc** [comment]
Closing. Country level filtering has now been implemented in the map/app.
